name: 自动抓取代理IP并提交

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 手动触发

jobs:
  update-proxy-list:
    name: 抓取代理IP并提交
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装依赖
        run: |
          npm install node-fetch

      - name: 运行抓取脚本
        run: |
          node pp-worker.js

      - name: 检查文件变更
        id: changes
        run: |
          if git diff --exit-code proxy-list.txt; then
            echo "没有文件变更"
            echo "::set-output name=has_changes::false"
          else
            echo "发现文件变更"
            echo "::set-output name=has_changes::true"
          fi

      - name: 提交文件变更
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "33571918@qq.com"
          git config --local user.name "Auto Proxy Updater"
          git add proxy-list.txt
          git commit -m "更新代理IP列表 $(date)"
          git push origin main
